<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Features\Authentication\" />
    <Folder Include="Features\Fees\" />
    <Folder Include="Features\Students\" />
    <Folder Include="Validators\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="8.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ERP.Domain\ERP.Domain.csproj" />
    <ProjectReference Include="..\ERP.Shared\ERP.Shared.csproj" />
  </ItemGroup>

</Project>
