<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Logging\" />
    <Folder Include="EmailService\" />
    <Folder Include="FileStorage\" />
    <Folder Include="Identity\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ERP.Application\ERP.Application.csproj" />
    <ProjectReference Include="..\ERP.Shared\ERP.Shared.csproj" />
  </ItemGroup>

</Project>
