<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.2">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Middleware\" />
    <Folder Include="Extensions\" />
    <Folder Include="Filters\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ERP.Application\ERP.Application.csproj" />
    <ProjectReference Include="..\ERP.Domain\ERP.Domain.csproj" />
    <ProjectReference Include="..\ERP.Infrastructure\ERP.Infrastructure.csproj" />
    <ProjectReference Include="..\ERP.Persistence\ERP.Persistence.csproj" />
    <ProjectReference Include="..\ERP.Shared\ERP.Shared.csproj" />
  </ItemGroup>

</Project>
